name: Deno

on:
  push:
  pull_request:

jobs:
  denofmt-and-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - uses: actions/checkout@v3

      - run: deno lint
      - run: deno fmt --check

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - uses: actions/checkout@v3

      - run: deno cache *.ts
      - run: deno check *.ts
